### PR TITLE
Post validation transformations

### PR DESCRIPTION
**Pull request by aew**
Various bugfixes and optimizations:
- Add test for execution on field arguments with variable bindings
- Build arguments, expand fragments, and inline types prior to execution phase
- Refactor executor to be simpler (delete the majority of the code)
- Warnings for library users accidentally doing parsing / validation in the inner loop
- Bugfix - break on undefined variables, don't traverse deeper
- Bugfix - add test for missing required variables, and support default values for variables
- Bugfix - guard against null values for non-null types in the execution phase
- Bugfix - support execution with inline fragments
- Bugfix - validation for missing root fields
- Bugfix - required arguments fulfilled by required variables
- Add preparation and memoization as an example in executor test
- Optionally add a `:resolver` key to state when validating a statement to inline resolver-fns prior to execution (and add example to executor test case)
- Streamline statement validation output - remove :state key in the absence of errors
- Add a spec for statement validation output and ensure test cases conform
- Add starwars test case from the `graphql-clj-starter project`
- Bugfix for introspection resolution - isDeprecated is a non-null field

Addresses:
* https://github.com/tendant/graphql-clj/issues/42
* https://github.com/tendant/graphql-clj/issues/36 - doesn't change the current approach, but removes much of the complexity from it
* https://github.com/tendant/graphql-clj/issues/35
* https://github.com/tendant/graphql-clj/issues/43 - partial fix - relaxes validation constraint for now until we can resolve object equality for these specs - better than blocking valid statements in the meantime.

Related: 
* https://github.com/tendant/graphql-clj-starter/pull/1
* https://github.com/xsc/graphql-clj-bench/pull/2

### CODE REVIEW

**Comment by aew** [comment]
I've found a bug in the `parent-type-name` for the resolver - I'll fix this.

**Comment by aew** [comment]
The changes to the execution phase in this PR have the following effect on runtime performance (from https://github.com/xsc/graphql-clj-bench/pull/2):

version `0.1.19`:
```
Goal:  Verifying GraphQL query execution overhead when caching query string parsing and validation.
-----
Case:  :nested-query
Evaluation count : 2248140 in 60 samples of 37469 calls.
             Execution time mean : 27.192858 µs
    Execution time std-deviation : 963.805891 ns
   Execution time lower quantile : 25.988479 µs ( 2.5%)
   Execution time upper quantile : 29.398797 µs (97.5%)
```

version `0.1.20-SNAPSHOT`:
```
Goal:  Verifying GraphQL query execution overhead when caching query string parsing and validation.
-----
Case:  :nested-query
Evaluation count : 9175500 in 60 samples of 152925 calls.
             Execution time mean : 6.838653 µs
    Execution time std-deviation : 288.873382 ns
   Execution time lower quantile : 6.431759 µs ( 2.5%)
   Execution time upper quantile : 7.298638 µs (97.5%)
```

version `0.1.20-SNAPSHOT` with inline resolver functions:
```
Goal:  Verifying GraphQL query execution overhead with inline resolver functions.
-----
Case:  :nested-query
Evaluation count : 9681840 in 60 samples of 161364 calls.
             Execution time mean : 6.066969 µs
    Execution time std-deviation : 114.881843 ns
   Execution time lower quantile : 5.898743 µs ( 2.5%)
   Execution time upper quantile : 6.283401 µs (97.5%)
```

**Comment by aew** [comment]
Validated statement output should now be roughly equivalent in size to the parsed data structure

**Comment by aew** [comment]
The changes to the executor in this PR have the following impact on execution runtime performance:

version `1.19.0` with memoization

```
Evaluation count : 1479300 in 60 samples of 24655 calls.
             Execution time mean : 41.074870 µs
    Execution time std-deviation : 649.450286 ns
   Execution time lower quantile : 40.055590 µs ( 2.5%)
   Execution time upper quantile : 42.387063 µs (97.5%)
```

version `1.20.0-SNAPSHOT` with memoization

```
Evaluation count : 4248660 in 60 samples of 70811 calls.
             Execution time mean : 14.944263 µs
    Execution time std-deviation : 575.873227 ns
   Execution time lower quantile : 14.091584 µs ( 2.5%)
   Execution time upper quantile : 16.059733 µs (97.5%)
```

version `1.20.0-SNAPSHOT` with memoization and inline resolver functions

```
Evaluation count : 6908580 in 60 samples of 115143 calls.
             Execution time mean : 8.915279 µs
    Execution time std-deviation : 160.062685 ns
   Execution time lower quantile : 8.687222 µs ( 2.5%)
   Execution time upper quantile : 9.306784 µs (97.5%)
```

From: https://github.com/xsc/graphql-clj-bench/pull/2

**Comment by tendant** [comment]
Found a bug: https://github.com/tendant/graphql-clj-starter/tree/testing-validation-loc

Required List field has wrong kind :OBJCET instead of :LIST.

**Comment by xsc** [comment]
@tendant Stuff like that should probably be verified within the inteospection unit tests, right?

**Comment by aew** [comment]
I've fixed this bug, and added some unit test cases.

**Comment by tendant** [comment]
Super. I will test it and merge it soon.

**Pull request merged**
